language: go
go:
  - 1.5

env:
  global:
    - PATH="$GOPATH/bin:$PATH"
    - RELEASES_PATH=/tmp/releases

script:
  - go test -v

before_deploy:
  - go get github.com/laher/goxc
  - goxc -tasks 'xc archive' -bc 'windows darwin linux' -d "$RELEASES_PATH" -resources-include 'README*'

deploy:
  provider: releases
  api_key:
    secure: Arie74KB6IFBpWo3X6HNflRO5TRsbguZnFqAMliNGr0QrJkYF9Q+yXwtrE98U7hUJRhM08TIK3eHaT3jzHJ82kqAC+S2DCVh6AQ+yxyKpqqX4x4ixAu/l3IqJif+Rmnbx0IDePox5tLHoc1pnqLEx/BIe2t5ErAgOen6bfKtsVb3ZzsYHp4IYPFPNo20rbCj8leRp8SCusD57XUigU+6TtwGk3ILQ+HP59KcUvQan9IV8adiwk/BtYyD50YWDpUj6pEMZva4kQBvpQTfogz7yy3BN/PJAay/da70bIs6B5+AITSpQo2uZ5Wkcpc9j3MnpdrT/5XAu3OYtLya/Oi0nnUCmug+bmoMxU+JTB0roFaQ7eacq1JcxDe9Mm7HlkxTnfuqBY5kW2ZWtqG4oh6rysH+0OlH94K9lfxoP+K1ykLAF0dd+q1WMNZs88BQtmsl+WQ6AiXmZXyYwrjmfKAdMDXDoF9e1GMYZv0M19zBIDIu5yBOThBBK4QV4YLyCRbxkJEAfNHNlbqAHaCj9urSLffeIwzWd7Ys7iV5zADt94QlnYBv5v30tza8S6JblkmMdWjuo0/zMDNiBYi/ausFm2KAMO6aqK0Q1GuSprCd0bWSF0EQXyy0kOw0P2j1OSJhvKZsJEtwNggzy9irlTknDdAobD5NLAG83aSfNKoDLqk=
  file:
    - $RELEASES_PATH/snapshot/csvp_windows_386.zip
    - $RELEASES_PATH/snapshot/csvp_windows_amd64.zip
    - $RELEASES_PATH/snapshot/csvp_darwin_386.zip
    - $RELEASES_PATH/snapshot/csvp_darwin_amd64.zip
    - $RELEASES_PATH/snapshot/csvp_linux_386.tar.gz
    - $RELEASES_PATH/snapshot/csvp_linux_amd64.tar.gz
    - $RELEASES_PATH/snapshot/csvp_linux_arm.tar.gz
  on:
    repo: kusabashira/csvp
    tags: true
